"use strict";
var batman = "batman";
var linternaVerde = "Linterna verde";
var volcanNegro = "Volcan negro";
console.log(batman);
console.log(linternaVerde);
console.log(volcanNegro);
var concatenar = "Los h\u00E9roes: " + batman + "," + linternaVerde + ", " + volcanNegro;
var concat = "Los héroes: " + batman + "," + linternaVerde + ", " + volcanNegro;
console.log(concatenar);
